version: "3"
services:
    consul_server1:
        image: "duruo850/cosule:1.3.0_alpine3.8"
        container_name: "consul_server1"
        hostname: "consul_server1"
        restart: always
# 同一个机器上面不能使用多个容器共享volume，/consul/data里面还有consul的私人数据：比如node-id,这个是容器私有信息
# 分布式需要采用consul的集群同步
#        volumes:
#            - /consul/data:/consul/data
#            - /consul/config:/consul/config
        ports:
            - "8300-8302:8300-8302"
            - "8301-8302:8301-8302/udp"
        command: " -server -bootstrap-expect 3"
    consul_server2:
        image: "duruo850/cosule:1.3.0_alpine3.8"
        container_name: "consul_server2"
        hostname: "consul_server2"
        restart: always
# 同一个机器上面不能使用多个容器共享volume，/consul/data里面还有consul的私人数据：比如node-id,这个是容器私有信息
# 分布式需要采用consul的集群同步
#        volumes:
#            - /consul/data:/consul/data
#            - /consul/config:/consul/config
        ports:
            - "8300-8302"
            - "8301-8302/udp"
        links:
            - "consul_server1:consul_server1"
        command: " -server -join consul_server1"
    consul_server3:
        image: "duruo850/cosule:1.3.0_alpine3.8"
        container_name: "consul_server3"
        hostname: "consul_server3"
        restart: always
# 同一个机器上面不能使用多个容器共享volume，/consul/data里面还有consul的私人数据：比如node-id,这个是容器私有信息
# 分布式需要采用consul的集群同步
#        volumes:
#            - /consul/data:/consul/data
#            - /consul/config:/consul/config
        ports:
            - "8300-8302"
            - "8301-8302/udp"
        links:
            - "consul_server1:consul_server1"
        command: " -server -join consul_server1"

    consul_web:
        image: "duruo850/cosule:1.3.0_alpine3.8"
        container_name: "consul_web"
        hostname: "consul_web"
        restart: always
# 同一个机器上面不能使用多个容器共享volume，/consul/data里面还有consul的私人数据：比如node-id,这个是容器私有信息
# 分布式需要采用consul的集群同步
#        volumes:
#            - /consul/data:/consul/data
#            - /consul/config:/consul/config
        ports:
            - "8400:8400"
            - "8500:8500"
            - "8600:53"
        links:
            - "consul_server1:consul_server1"
        command: " -server -join consul_server1"