#!/bin/sh
set -e

REDIS_CONF=/usr/local/bin/redis.conf
REDIS_PASSWORD=${REDIS_PASSWORD:-}
REDIS_HOST=${REDIS_HOST:-"0.0.0.0"}

update_conf() {
    # 由于conf有可能作为volume，所以只能采用cp方式，不能采用mv，vim等方式，这种方式容器内同步到宿主机有问题
    cp $REDIS_CONF /tmp/redis.conf

    if [ -n "$REDIS_PASSWORD" ]; then
        sed -i "s%^# requirepass foobared%requirepass $REDIS_PASSWORD%" /tmp/redis.conf
    fi
    sed -i "s%^bind 127.0.0.1%bind $REDIS_HOST%" /tmp/redis.conf

    cp /tmp/redis.conf $REDIS_CONF
    rm /tmp/redis.conf
}


if [ ! -f "/tmp/is_init" ]; then
  touch /tmp/is_init
  update_conf
fi

echo "Starting redis-server..."
exec docker-entrypoint.sh "$@"




